#spring:
#  application:
#    name: spring-medicine
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=yes&characterEncoding=UTF-8
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: SELECT 1
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        jdbc.time_zone: UTC
#  output:
#    ansi:
#      enabled: always
#server:
#  port: ${SERVER_PORT}

spring:
  application:
    name: spring-medicine
  datasource:
    url:  jdbc:mysql://localhost:3306/spring-medicine?autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Aristo070
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.time_zone: UTC
  mvc:
    static-path-pattern: /static/**
server:
  port: 8080